### ISSUE TITLE
Removal of Primitives

### ISSUE THREAD

**Issue by TheAndreiM** [juliarLang/juliarFuture#10]
PrintLine and Print is currently using primitives. It would be best to somehow get rid of them so that we can get rid of that dependency. . Any help would be appreciated.

**Comment by donreamey** [comment]
What do you mean dependency? Dependency on what?

**Comment by TheAndreiM** [comment]
Don't we rely on Primitives class for print and printLine function calls?

**Comment by donreamey** [comment]
if you look at the Primitives class it is using FileReader, BufferedReader for opening / reading a file and System.out.println for writing to the console. 

We can't get rid of them. I'm not sure why you would want to.

**Comment by TheAndreiM** [comment]
Alright, I am marking it as non-issue.
